In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("dataset.csv")

In [3]:
df.head()

,Unnamed: 0,date,time,ticket_number,article,Quantity,unit_price
0,0,2021-01-02,08:38,150040.0,BAGUETTE,1.0,"0,90 €"
1,1,2021-01-02,08:38,150040.0,PAIN AU CHOCOLAT,3.0,"1,20 €"
2,4,2021-01-02,09:14,150041.0,PAIN AU CHOCOLAT,2.0,"1,20 €"
3,5,2021-01-02,09:14,150041.0,PAIN,1.0,"1,15 €"
4,8,2021-01-02,09:25,150042.0,TRADITIONAL BAGUETTE,5.0,"1,20 €"

In [4]:
df.columns

Index(['Unnamed: 0', 'date', 'time', 'ticket_number', 'article', 'Quantity',
       'unit_price'],
      dtype='object')

In [5]:
df.drop("Unnamed: 0",axis=1,inplace=True)

In [6]:
df

,date,time,ticket_number,article,Quantity,unit_price
0,2021-01-02,08:38,150040.0,BAGUETTE,1.0,"0,90 €"
1,2021-01-02,08:38,150040.0,PAIN AU CHOCOLAT,3.0,"1,20 €"
2,2021-01-02,09:14,150041.0,PAIN AU CHOCOLAT,2.0,"1,20 €"
3,2021-01-02,09:14,150041.0,PAIN,1.0,"1,15 €"
4,2021-01-02,09:25,150042.0,TRADITIONAL BAGUETTE,5.0,"1,20 €"
...,...,...,...,...,...,...
234000,2022-09-30,18:52,288911.0,COUPE,1.0,"0,15 €"
234001,2022-09-30,18:52,288911.0,BOULE 200G,1.0,"1,20 €"
234002,2022-09-30,18:52,288911.0,COUPE,2.0,"0,15 €"
234003,2022-09-30,18:55,288912.0,TRADITIONAL BAGUETTE,1.0,"1,30 €"
234004,2022-09-30,18:56,288913.0,TRADITIONAL BAGUETTE,1.0,"1,30 €"

In [7]:
df.shape[0]

234005

In [8]:

df.dropna(inplace=True)
df.shape[0]

234005

In [9]:
df.article.unique()

array(['BAGUETTE', 'PAIN AU CHOCOLAT', 'PAIN', 'TRADITIONAL BAGUETTE',
       'CROISSANT', 'BANETTE', 'BANETTINE', 'SPECIAL BREAD', 'COUPE',
       'SAND JB EMMENTAL', 'KOUIGN AMANN', 'BOULE 200G', 'BOULE 400G',
       'GAL FRANGIPANE 6P', 'CAMPAGNE', 'MOISSON', 'CAFE OU EAU',
       'BRIOCHE', 'CEREAL BAGUETTE', 'SEIGLE', 'COMPLET',
       'DIVERS PATISSERIE', 'GAL FRANGIPANE 4P', 'COOKIE', 'FICELLE',
       'PAIN AUX RAISINS', 'GAL POMME 6P', 'GAL POMME 4P', 'FINANCIER X5',
       'VIK BREAD', 'DIVERS VIENNOISERIE', 'GACHE', 'SANDWICH COMPLET',
       'PAIN BANETTE', 'GRAND FAR BRETON', 'QUIM BREAD',
       'SPECIAL BREAD KG', 'GD KOUIGN AMANN', 'BOULE POLKA',
       'DEMI BAGUETTE', 'CHAUSSON AUX POMMES', 'BAGUETTE GRAINE',
       'DIVERS CONFISERIE', 'SUCETTE', 'DIVERS BOULANGERIE',
       'BOISSON 33CL', 'PATES', 'FORMULE SANDWICH', 'DIVERS SANDWICHS',
       'CROISSANT AMANDES', 'PAIN CHOCO AMANDES', 'SACHET VIENNOISERIE',
       'NANTAIS', 'CHOCOLAT', 'PAIN S/SEL', 'FONDANT CHOCOLAT',
       'GAL POIRE CHOCO 6P', 'GAL POIRE CHOCO 4P', 'GALETTE 8 PERS',
       'SAND JB', 'SACHET DE CROUTON', 'GRANDE SUCETTE', 'DEMI PAIN',
       'TARTELETTE', 'FLAN', 'PARIS BREST', 'SAVARIN', 'FLAN ABRICOT',
       'BAGUETTE APERO', 'MILLES FEUILLES', 'CHOU CHANTILLY', 'ECLAIR',
       'ROYAL 4P', 'TARTE FRUITS 6P', 'TARTE FRUITS 4P', 'NOIX JAPONAISE',
       'THE', 'BRIOCHETTE', 'ROYAL 6P', 'ECLAIR FRAISE PISTACHE', '.',
       'GD FAR BRETON', 'TRIANGLES', 'TROPEZIENNE',
       'TROPEZIENNE FRAMBOISE', 'ROYAL', 'TARTE FRAISE 6P',
       'TARTELETTE FRAISE', 'TARTE FRAISE 4PER', 'FRAISIER',
       'NID DE POULE', 'TARTELETTE CHOC', 'PAIN DE MIE', 'CRUMBLE',
       'FINANCIER', 'DIVERS BOISSONS', 'CAKE', 'VIENNOISE', 'TRAITEUR',
       'PAIN GRAINES', 'PLATPREPARE6,50', 'PLATPREPARE5,50',
       'PLATPREPARE7,00', 'FORMULE PLAT PREPARE', 'ST HONORE', 'BROWNIES',
       'RELIGIEUSE', 'PLATPREPARE6,00', 'DELICETROPICAL',
       'CRUMBLECARAMEL OU PISTAE', 'PT NANTAIS', 'GD NANTAIS',
       'DOUCEUR D HIVER', 'TROIS CHOCOLAT', 'ARTICLE 295', 'TARTE FINE',
       'ENTREMETS', 'BRIOCHE DE NOEL', 'FRAMBOISIER', 'BUCHE 4PERS',
       'BUCHE 6PERS', 'GD PLATEAU SALE', 'BUCHE 8PERS', 'PT PLATEAU SALE',
       'REDUCTION SUCREES 12', 'PAIN NOIR', 'REDUCTION SUCREES 24',
       'BOTTEREAU', 'MERINGUE', 'PALMIER', 'PAILLE', 'PLAT 6.50E',
       'PLAT 7.60E', 'PLAT 7.00', 'PLAT', 'PLAT 8.30E', 'FORMULE PATE',
       'GUERANDAIS', 'PALET BRETON', 'CARAMEL NOIX', 'MACARON',
       '12 MACARON', 'ARMORICAIN', 'PLAQUE TARTE 25P', 'SABLE F  P',
       'PAIN SUISSE PEPITO', 'TULIPE', 'TARTELETTE COCKTAIL',
       'SACHET DE VIENNOISERIE'], dtype=object)

In [10]:
produtos = sorted(df.article.unique())

for produto in produtos:
    print("Produto: ",produto)

Produto:  .
Produto:  12 MACARON
Produto:  ARMORICAIN
Produto:  ARTICLE 295
Produto:  BAGUETTE
Produto:  BAGUETTE APERO
Produto:  BAGUETTE GRAINE
Produto:  BANETTE
Produto:  BANETTINE
Produto:  BOISSON 33CL
Produto:  BOTTEREAU
Produto:  BOULE 200G
Produto:  BOULE 400G
Produto:  BOULE POLKA
Produto:  BRIOCHE
Produto:  BRIOCHE DE NOEL
Produto:  BRIOCHETTE
Produto:  BROWNIES
Produto:  BUCHE 4PERS
Produto:  BUCHE 6PERS
Produto:  BUCHE 8PERS
Produto:  CAFE OU EAU
Produto:  CAKE
Produto:  CAMPAGNE
Produto:  CARAMEL NOIX
Produto:  CEREAL BAGUETTE
Produto:  CHAUSSON AUX POMMES
Produto:  CHOCOLAT
Produto:  CHOU CHANTILLY
Produto:  COMPLET
Produto:  COOKIE
Produto:  COUPE
Produto:  CROISSANT
Produto:  CROISSANT AMANDES
Produto:  CRUMBLE
Produto:  CRUMBLECARAMEL OU PISTAE
Produto:  DELICETROPICAL
Produto:  DEMI BAGUETTE
Produto:  DEMI PAIN
Produto:  DIVERS BOISSONS
Produto:  DIVERS BOULANGERIE
Produto:  DIVERS CONFISERIE
Produto:  DIVERS PATISSERIE
Produto:  DIVERS SANDWICHS
Produto:  DIVERS VIENNOISERIE
Produto:  DOUCEUR D HIVER
Produto:  ECLAIR
Produto:  ECLAIR FRAISE PISTACHE
Produto:  ENTREMETS
Produto:  FICELLE
Produto:  FINANCIER
Produto:  FINANCIER X5
Produto:  FLAN
Produto:  FLAN ABRICOT
Produto:  FONDANT CHOCOLAT
Produto:  FORMULE PATE
Produto:  FORMULE PLAT PREPARE
Produto:  FORMULE SANDWICH
Produto:  FRAISIER
Produto:  FRAMBOISIER
Produto:  GACHE
Produto:  GAL FRANGIPANE 4P
Produto:  GAL FRANGIPANE 6P
Produto:  GAL POIRE CHOCO 4P
Produto:  GAL POIRE CHOCO 6P
Produto:  GAL POMME 4P
Produto:  GAL POMME 6P
Produto:  GALETTE 8 PERS
Produto:  GD FAR BRETON
Produto:  GD KOUIGN AMANN
Produto:  GD NANTAIS
Produto:  GD PLATEAU SALE
Produto:  GRAND FAR BRETON
Produto:  GRANDE SUCETTE
Produto:  GUERANDAIS
Produto:  KOUIGN AMANN
Produto:  MACARON
Produto:  MERINGUE
Produto:  MILLES FEUILLES
Produto:  MOISSON
Produto:  NANTAIS
Produto:  NID DE POULE
Produto:  NOIX JAPONAISE
Produto:  PAILLE
Produto:  PAIN
Produto:  PAIN AU CHOCOLAT
Produto:  PAIN AUX RAISINS
Produto:  PAIN BANETTE
Produto:  PAIN CHOCO AMANDES
Produto:  PAIN DE MIE
Produto:  PAIN GRAINES
Produto:  PAIN NOIR
Produto:  PAIN S/SEL
Produto:  PAIN SUISSE PEPITO
Produto:  PALET BRETON
Produto:  PALMIER
Produto:  PARIS BREST
Produto:  PATES
Produto:  PLAQUE TARTE 25P
Produto:  PLAT
Produto:  PLAT 6.50E
Produto:  PLAT 7.00
Produto:  PLAT 7.60E
Produto:  PLAT 8.30E
Produto:  PLATPREPARE5,50
Produto:  PLATPREPARE6,00
Produto:  PLATPREPARE6,50
Produto:  PLATPREPARE7,00
Produto:  PT NANTAIS
Produto:  PT PLATEAU SALE
Produto:  QUIM BREAD
Produto:  REDUCTION SUCREES 12
Produto:  REDUCTION SUCREES 24
Produto:  RELIGIEUSE
Produto:  ROYAL
Produto:  ROYAL 4P
Produto:  ROYAL 6P
Produto:  SABLE F  P
Produto:  SACHET DE CROUTON
Produto:  SACHET DE VIENNOISERIE
Produto:  SACHET VIENNOISERIE
Produto:  SAND JB
Produto:  SAND JB EMMENTAL
Produto:  SANDWICH COMPLET
Produto:  SAVARIN
Produto:  SEIGLE
Produto:  SPECIAL BREAD
Produto:  SPECIAL BREAD KG
Produto:  ST HONORE
Produto:  SUCETTE
Produto:  TARTE FINE
Produto:  TARTE FRAISE 4PER
Produto:  TARTE FRAISE 6P
Produto:  TARTE FRUITS 4P
Produto:  TARTE FRUITS 6P
Produto:  TARTELETTE
Produto:  TARTELETTE CHOC
Produto:  TARTELETTE COCKTAIL
Produto:  TARTELETTE FRAISE
Produto:  THE
Produto:  TRADITIONAL BAGUETTE
Produto:  TRAITEUR
Produto:  TRIANGLES
Produto:  TROIS CHOCOLAT
Produto:  TROPEZIENNE
Produto:  TROPEZIENNE FRAMBOISE
Produto:  TULIPE
Produto:  VIENNOISE
Produto:  VIK BREAD

In [11]:
valores = df.unit_price.unique()

for valor in valores:
    print(valor)

0,90 €
1,20 €
1,15 €
1,10 €
1,05 €
0,60 €
2,40 €
0,15 €
3,50 €
2,10 €
1,50 €
12,00 €
1,80 €
2,00 €
1,00 €
5,00 €
1,25 €
0,00 €
8,00 €
1,40 €
3,00 €
2,50 €
4,00 €
4,50 €
7,00 €
6,00 €
4,80 €
7,50 €
1,60 €
0,45 €
1,30 €
0,30 €
6,50 €
16,00 €
24,00 €
0,07 €
10,00 €
9,00 €
2,80 €
11,00 €
0,80 €
0,40 €
4,20 €
3,20 €
18,00 €
44,00 €
0,25 €
4,75 €
22,00 €
14,00 €
0,70 €
5,40 €
13,00 €
9,10 €
8,50 €
5,50 €
17,00 €
9,50 €
21,00 €
5,45 €
12,50 €
22,50 €
35,00 €
15,00 €
13,50 €
3,75 €
28,00 €
14,50 €
14,60 €
8,30 €
9,80 €
7,60 €
10,50 €
15,20 €
16,60 €
12,60 €
8,90 €
11,65 €
6,85 €
9,60 €
10,30 €
20,60 €
10,40 €
11,10 €
14,65 €
15,60 €
23,60 €
0,50 €
21,60 €
0,95 €
0,65 €
2,20 €
1,90 €
1,70 €
2,60 €
8,60 €
1,35 €
4,90 €
6,80 €
5,80 €
10,60 €
5,32 €
0,33 €
5,30 €
7,30 €
5,70 €
17,10 €
22,80 €
9,30 €
6,60 €
4,40 €
3,30 €
0,75 €
2,30 €
5,20 €
2,70 €
6,40 €
3,60 €
11,62 €
60,00 €
26,00 €
4,70 €
30,00 €

In [12]:
print(f"Mais caro: {max(valores)}\nMais barato: {min(valores)}")

print(f"Mediana: {np.median(valores)}")

print(f"\nMédia: {np.mean(valores)}\nDesvio Padrão: {np.std(valores)}\nVariancia: {np.var(valores)}")

Mais caro: 9,80 €
Mais barato: 0,00 €

TypeError: ufunc 'divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''